// AUTO-GENERIERT aus Supabase via scripts/build-roadmap.mjs — NICHT manuell editieren!
// Letzte Aktualisierung: 2026-07-11T12:01:10.705Z

const roadmapData = [
  {
    id: "8ad8e9fd-e975-452e-bd33-a861e9102943",
    scope: "portfolio",
    project_slug: null,
    title_de: `Admin Panel — Phase 1 Abschluss`,
    title_en: `Admin Panel — Phase 1 Completion`,
    title_ar: `لوحة الإدارة — إتمام المرحلة الأولى`,
    description_de: `Changelog-Admin + Blog/Thoughts-Editor im Admin Panel. Letzter Schritt von Phase 1 bevor das Portfolio öffentlich geht.`,
    description_en: `Changelog admin + Blog/Thoughts editor in the admin panel. Final step of Phase 1 before the portfolio goes public.`,
    description_ar: `إدارة سجل التغييرات ومحرر المدونة في لوحة الإدارة. الخطوة الأخيرة من المرحلة الأولى.`,
    phase_label_de: `Phase 1 — aktiv`,
    phase_label_en: `Phase 1 — active`,
    phase_label_ar: `المرحلة 1 — نشطة`,
    status: "completed",
    sort_order: 0
  },
  {
    id: "f6474ca9-00d3-449a-9b1e-fac7e1f3867a",
    scope: "portfolio",
    project_slug: null,
    title_de: `Öffentliche Changelog-Seite`,
    title_en: `Public Changelog Page`,
    title_ar: `صفحة سجل التغييرات العامة`,
    description_de: `Eigene /changelog-Seite — alle Releases nach Version, Datum und Kategorie gelistet. Footer-Link, vollständig mehrsprachig.`,
    description_en: `Own /changelog page — all releases listed by version, date, and category. Footer link, fully multilingual.`,
    description_ar: `صفحة /changelog خاصة تعرض جميع الإصدارات مرتبة حسب الإصدار والتاريخ والفئة.`,
    phase_label_de: `Phase 2`,
    phase_label_en: `Phase 2`,
    phase_label_ar: `المرحلة 2`,
    status: "planned",
    sort_order: 10
  },
  {
    id: "d7c31c08-438e-4592-baf0-b2768433fdfc",
    scope: "portfolio",
    project_slug: null,
    title_de: `GitHub Activity Widget`,
    title_en: `GitHub Activity Widget`,
    title_ar: `أداة نشاط GitHub`,
    description_de: `Live GitHub-Aktivitäten auf der Startseite — Contribution-Graph oder letzte Commits. Belegt aktives Development ohne ein Wort.`,
    description_en: `Live GitHub activity on the homepage — contribution graph or recent commits. Proves active development without a word.`,
    description_ar: `نشاط GitHub المباشر على الصفحة الرئيسية — يثبت التطوير النشط دون كلمة.`,
    phase_label_de: `Phase 2`,
    phase_label_en: `Phase 2`,
    phase_label_ar: `المرحلة 2`,
    status: "planned",
    sort_order: 30
  },
  {
    id: "58ebf158-6f56-48da-9f42-60f26a9b3681",
    scope: "portfolio",
    project_slug: null,
    title_de: `Demo-Video Integration`,
    title_en: `Demo Video Integration`,
    title_ar: `تكامل الفيديو التوضيحي`,
    description_de: `Kurze Demo-Videos direkt in Projektseiten — StudyNexus zuerst. Lazy-Loading, kein Autoplay, kein Performance-Impact.`,
    description_en: `Short demo videos directly in project pages — StudyNexus first. Lazy loading, no autoplay, no performance impact.`,
    description_ar: `فيديوهات توضيحية قصيرة في صفحات المشاريع مباشرةً.`,
    phase_label_de: `Phase 2`,
    phase_label_en: `Phase 2`,
    phase_label_ar: `المرحلة 2`,
    status: "planned",
    sort_order: 40
  },
  {
    id: "2844d4cd-3946-4036-99cf-9768f825db37",
    scope: "portfolio",
    project_slug: null,
    title_de: `Project Status Indicators`,
    title_en: `Project Status Indicators`,
    title_ar: `مؤشرات حالة المشروع`,
    description_de: `Live-Status-Badges auf Projektkarten — "In Entwicklung", "Beta", "Live". Gesteuert aus dem Admin Panel.`,
    description_en: `Live status badges on project cards — "In Development", "Beta", "Live". Controlled from the admin panel.`,
    description_ar: `شارات الحالة المباشرة على بطاقات المشاريع — مدارة من لوحة الإدارة.`,
    phase_label_de: `Phase 2`,
    phase_label_en: `Phase 2`,
    phase_label_ar: `المرحلة 2`,
    status: "planned",
    sort_order: 50
  },
  {
    id: "b0807ae4-54ce-4f0c-9cb2-d1dc827d9aa6",
    scope: "portfolio",
    project_slug: null,
    title_de: `Dark Mode`,
    title_en: `Dark Mode`,
    title_ar: ``,
    description_de: `Light/Dark Mode Toggle unter Beibehaltung der Vanilla-Performance. Status-Speicherung via LocalStorage.`,
    description_en: `Light/Dark Mode toggle while keeping vanilla performance. State persistence via LocalStorage.`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 60
  },
  {
    id: "a49dece6-55e1-47ec-86d3-12e62582acb1",
    scope: "portfolio",
    project_slug: null,
    title_de: `Blog / Thoughts`,
    title_en: `Blog / Thoughts`,
    title_ar: ``,
    description_de: `Eigene /thoughts Sektion — kurze Posts, LinkedIn-Stil aber individuell. Verwaltet im Admin Panel.`,
    description_en: `Own /thoughts section — short posts, LinkedIn-style but individual. Managed in Admin Panel.`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 70
  },
  {
    id: "9952451c-c456-4cc6-bc24-f686756bdc8f",
    scope: "portfolio",
    project_slug: null,
    title_de: `Animierte Seitenübergänge`,
    title_en: `Animated Page Transitions`,
    title_ar: `انتقالات الصفحات المتحركة`,
    description_de: `Smooth Seitenübergänge via View Transitions API — kein Framework, kein Layout-Shift, kein Performance-Impact.`,
    description_en: `Smooth page transitions via View Transitions API — no framework, no layout shift, no performance impact.`,
    description_ar: `انتقالات سلسة بين الصفحات باستخدام View Transitions API بدون مكتبات.`,
    phase_label_de: `Phase 3`,
    phase_label_en: `Phase 3`,
    phase_label_ar: `المرحلة 3`,
    status: "planned",
    sort_order: 80
  },
  {
    id: "2a7749ba-88d4-4386-b182-d9e2be3f201c",
    scope: "portfolio",
    project_slug: null,
    title_de: `ES Modules Migration`,
    title_en: `ES Modules Migration`,
    title_ar: `ترحيل وحدات ES`,
    description_de: `Umstieg auf native ES Modules im Browser — saubere Scope-Isolation, kein globaler Window-Clutter, ohne Bundler.`,
    description_en: `Switch to native ES Modules in the browser — clean scope isolation, no global window clutter, no bundler needed.`,
    description_ar: `التحول إلى وحدات ES الأصلية في المتصفح لعزل النطاق بشكل نظيف.`,
    phase_label_de: `Phase 3`,
    phase_label_en: `Phase 3`,
    phase_label_ar: `المرحلة 3`,
    status: "planned",
    sort_order: 90
  },
  {
    id: "2eaa2ef7-80db-4492-9536-97d193350eee",
    scope: "portfolio",
    project_slug: null,
    title_de: `Arabisch (AR) — Dritte Sprache`,
    title_en: `Arabic (AR) — Third Language`,
    title_ar: ``,
    description_de: `Vollständige AR-Übersetzung + RTL-Support. Language Switcher: DE → EN → AR.`,
    description_en: `Full AR translation + RTL support. Language switcher: DE → EN → AR.`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 100
  },
  {
    id: "929c099e-cd6c-4ba4-ac26-36b9d44cf84b",
    scope: "project",
    project_slug: "html-cv",
    title_de: `Core Engine`,
    title_en: `Core Engine`,
    title_ar: ``,
    description_de: `HTML Structure & Print CSS`,
    description_en: `HTML Structure & Print CSS`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 1
  },
  {
    id: "d834afbd-68bb-42c1-b5f2-b1967ebef1eb",
    scope: "project",
    project_slug: "html-cv",
    title_de: `Privacy Layer`,
    title_en: `Privacy Layer`,
    title_ar: ``,
    description_de: `Git Hooks & Data Separation`,
    description_en: `Git Hooks & Data Separation`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 2
  },
  {
    id: "7f58e636-62bc-46a0-974a-d4724f9f1a01",
    scope: "project",
    project_slug: "html-cv",
    title_de: `JSON Import`,
    title_en: `JSON Import`,
    title_ar: ``,
    description_de: `Lebenslauf-Daten aus JSON-Datei laden statt Hardcoding.`,
    description_en: `Load CV data from JSON file instead of hardcoding.`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 3
  },
  {
    id: "56e64090-524d-4797-ab80-e88ef44cd767",
    scope: "project",
    project_slug: "html-cv",
    title_de: `PDF-Auto-Gen`,
    title_en: `PDF-Auto-Gen`,
    title_ar: ``,
    description_de: `Automatischer PDF-Export via Node.js (Puppeteer) bei jedem Git Push.`,
    description_en: `Automatic PDF export via Node.js (Puppeteer) on every Git Push.`,
    description_ar: ``,
    phase_label_de: ``,
    phase_label_en: ``,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 4
  },
  {
    id: "a61dea86-86b5-4fd8-90b0-b3e5ad30c4e8",
    scope: "project",
    project_slug: "studynexus",
    title_de: `Foundation: Auth, DB & Docker`,
    title_en: `Foundation: Auth, DB & Docker`,
    title_ar: ``,
    description_de: `JWT Authentication, PostgreSQL-Schema mit Alembic, Docker Compose Stack mit 5 Services, Email-Verifikation via Resend API, vollständige Studienplan-CRUD mit GPA-Berechnung.`,
    description_en: `JWT authentication, PostgreSQL schema with Alembic, Docker Compose stack with 5 services, email verification via Resend API, complete study plan CRUD with GPA calculation.`,
    description_ar: ``,
    phase_label_de: `Sprint 1-2 ✓`,
    phase_label_en: `Sprint 1-2 ✓`,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 1
  },
  {
    id: "625965f7-9f5b-4196-b26b-8fab3219b9d4",
    scope: "project",
    project_slug: "studynexus",
    title_de: `Mission Control & Mobile`,
    title_en: `Mission Control & Mobile`,
    title_ar: ``,
    description_de: `Kanban Board (@dnd-kit), Schedule Board (15-Min CSS Grid), Dashboard Widgets, Mobile FAB, Agenda View für kleine Screens, TanStack Query Migration, vollständige i18n (DE/EN).`,
    description_en: `Kanban board (@dnd-kit), schedule board (15-min CSS grid), dashboard widgets, mobile FAB, agenda view, TanStack Query migration, full i18n (DE/EN).`,
    description_ar: ``,
    phase_label_de: `Sprint 3.x ✓`,
    phase_label_en: `Sprint 3.x ✓`,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 2
  },
  {
    id: "d94f0cd8-6f5e-481a-8066-69275d4961c1",
    scope: "project",
    project_slug: "studynexus",
    title_de: `BIN Prüfungsordnung Integration`,
    title_en: `BIN Exam Regulations Integration`,
    title_ar: ``,
    description_de: `37 BIN-Module aus 3 PDFs, Prüfungsart-System (PX/EA/R/BAA+Ko), §6-Voraussetzungen als DB-Constraints, MilestoneWidget, PO-Übersicht-Seite, GPA-Fix BIN-209.`,
    description_en: `37 BIN modules from 3 PDFs, exam-type system (PX/EA/R/BAA+Ko), §6 prerequisites as DB constraints, MilestoneWidget, PO overview page, GPA fix for BIN-209.`,
    description_ar: ``,
    phase_label_de: `Sprint 4 ✓`,
    phase_label_en: `Sprint 4 ✓`,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 3
  },
  {
    id: "8b6484d3-f70c-4d8a-a8a2-7d4e3ca09f48",
    scope: "project",
    project_slug: "studynexus",
    title_de: `Admin Panel — Enterprise Control Center`,
    title_en: `Admin Panel — Enterprise Control Center`,
    title_ar: ``,
    description_de: `14 Admin-Seiten, 35+ Endpunkte, Two-Layer Auth (JWT + Redis Sudo), Audit-Log, Analytics (Recharts), JSON-Bulk-Import, 122/122 Tests grün.`,
    description_en: `14 admin pages, 35+ endpoints, two-layer auth (JWT + Redis Sudo), audit log, analytics (Recharts), JSON bulk import, 122/122 tests green.`,
    description_ar: ``,
    phase_label_de: `Sprint 5 ✓`,
    phase_label_en: `Sprint 5 ✓`,
    phase_label_ar: ``,
    status: "completed",
    sort_order: 4
  },
  {
    id: "5649cf3c-1d5f-4dd8-a9d4-a95639ad5f77",
    scope: "project",
    project_slug: "studynexus",
    title_de: `Security Audit & Email-Templates`,
    title_en: `Security Audit & Email Templates`,
    title_ar: ``,
    description_de: `Admin-API-Rate-Limiting, Toast-Notifications bei API-Errors, E-Mail-Templates für Passwort-Reset, UI-Polishing und Dropdown-Auswahl für UUID-Felder.`,
    description_en: `Admin API rate limiting, toast notifications for API errors, email templates for password reset, UI polishing and dropdown selectors for UUID fields.`,
    description_ar: ``,
    phase_label_de: `Sprint 6`,
    phase_label_en: `Sprint 6`,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 5
  },
  {
    id: "003ccca8-bb6e-4918-b3f9-aecabc723b92",
    scope: "project",
    project_slug: "studynexus",
    title_de: `Production Launch für die HsH`,
    title_en: `Production Launch for HsH`,
    title_ar: ``,
    description_de: `Öffentlicher Launch für alle HS Hannover Studierenden. Onboarding-Flow mit vorausgefüllten Prüfungsordnungen. Gamification: XP, Badges, Streaks.`,
    description_en: `Public launch for all HS Hannover students. Onboarding flow with pre-filled exam regulations. Gamification: XP, badges, streaks.`,
    description_ar: ``,
    phase_label_de: `v1.0 — Ziel`,
    phase_label_en: `v1.0 — Goal`,
    phase_label_ar: ``,
    status: "planned",
    sort_order: 6
  }
];

const changelogData = [
  {
    id: "8a71f4ce-b3ff-4ff1-9e20-138c9d604ab2",
    version: "v3.0.0",
    date: "2026-06-07",
    category: "feature",
    title_de: `Der große Relaunch — ein vollständig verwaltbares Portfolio-System`,
    title_en: `The Big Relaunch — A Fully Self-Managed Portfolio System`,
    title_ar: `إعادة الإطلاق الكبرى — نظام محفظة قابل للإدارة بالكامل`,
    description_de: `Der größte Sprung seit dem Start: Aus einer statischen Seite wird ein vollständig selbst verwaltetes System — dreisprachig, KI-gestützt, in jeder Ebene abgesichert, und weiterhin ohne ein einziges Frontend-Framework.<br><br>• <strong>Dreisprachigkeit mit echtem SEO</strong> — DE · EN · AR mit vollständigem Rechts-nach-links-Layout für Arabisch. Jede Sprache wird jetzt zusätzlich statisch vorgerendert (eigene URLs, hreflang) — Google indexiert jede Sprache separat, nicht nur Deutsch.<br><br>• <strong>KI-Twin „Ask Yusef · Neural Console"</strong> — mein Chat-Widget wurde komplett neu gestaltet: ein atmender AI-Ring-Button, Auto-Hide beim Scrollen, ein Vollbild-Sheet mit Wisch-Geste auf Mobile, Cmd/Ctrl+K zum Öffnen und kontextbewusste Frage-Vorschläge je nach Seite.<br><br>• <strong>Admin Panel „SPACE"</strong> — ein Apple-artiges Verwaltungswerkzeug mit ⌘K-Command-Palette, acht Bereichen (Projekte, Roadmap, Changelog, Blog, Übersetzungen, Medien, KI-Wissen, Wartungsmodus), einem Live-System-Health-Dashboard und vollständigem Aktivitätsprotokoll.<br><br>• <strong>Security-Fortress</strong> — vier unabhängige Sicherheitsebenen im Admin Panel: Zugangs-Whitelist, ein PIN als zweiter Faktor, Rate-Limiting gegen Missbrauch und Security-Header — bevor das Panel die echte Live-Seite verwaltet.<br><br>• <strong>Neue öffentliche Bereiche</strong> — ein mehrsprachiger Blog (Thoughts), dieser öffentliche Changelog (jetzt mit klickbaren Detail-Karten), eine dynamische Roadmap und ein Live-GitHub-Aktivitäts-Widget.<br><br>• <strong>Design-Neustart „Calm Cinema"</strong> — die Startseite als durchgehende Leinwand statt einzelner Blöcke, eine maus-folgende Aurora im Hero, cinematische Scroll-Übergänge, self-hosted Schriften und fluide Typografie.<br><br>• <strong>Barrierefreiheit & PWA</strong> — Skip-Links, vollständige Tastaturbedienbarkeit, kein Layout-Sprung beim Laden, installierbar und offline-fähig.<br><br>• <strong>Und jede Menge Feinschliff</strong> — von Grund auf auf Mobile getestet, Dutzende kleine Fehler behoben, jede Sprache und jeder Modus (Hell/Dunkel) doppelt geprüft.`,
    description_en: `The biggest leap since launch: a static page grows into a fully self-managed system — trilingual, AI-powered, hardened at every layer, and still without a single frontend framework.<br><br>• <strong>Trilingual with real SEO</strong> — DE · EN · AR with full right-to-left layout for Arabic. Every language is now statically pre-rendered (its own URLs, hreflang) — Google indexes each language separately, not just German.<br><br>• <strong>AI twin “Ask Yusef · Neural Console”</strong> — my chat widget got a full redesign: a breathing AI-ring button, auto-hide on scroll, a full-screen swipeable sheet on mobile, Cmd/Ctrl+K to open, and context-aware question suggestions per page.<br><br>• <strong>Admin panel “SPACE”</strong> — an Apple-inspired management tool with a ⌘K command palette, eight content areas (projects, roadmap, changelog, blog, translations, media, AI knowledge, maintenance mode), a live system-health dashboard, and a full activity log.<br><br>• <strong>Security fortress</strong> — four independent security layers protect the admin panel: access whitelist, a PIN as second factor, rate-limiting, and security headers — before it manages the real live site.<br><br>• <strong>New public sections</strong> — a multilingual blog (Thoughts), this public changelog (now with clickable detail cards), a dynamic roadmap, and a live GitHub activity widget.<br><br>• <strong>Design reset “Calm Cinema”</strong> — the homepage as one continuous canvas instead of separate blocks, a mouse-following aurora in the hero, cinematic scroll transitions, self-hosted fonts, and fluid typography.<br><br>• <strong>Accessibility & PWA</strong> — skip links, full keyboard operability, zero layout shift on load, installable and offline-capable.<br><br>• <strong>And a ton of polish</strong> — tested from the ground up on mobile, dozens of small bugs fixed, every language and theme (light/dark) checked twice.`,
    description_ar: `أكبر قفزة منذ الإطلاق: تتحوّل صفحة ثابتة إلى نظام قابل للإدارة بالكامل — ثلاثي اللغات، مدعوم بالذكاء الاصطناعي، محصَّن على كل مستوى، وما يزال دون أي إطار عمل أمامي.<br><br>• <strong>ثلاث لغات مع تحسين حقيقي لمحركات البحث</strong> — DE · EN · AR مع تخطيط كامل من اليمين إلى اليسار للعربية. أصبحت كل لغة الآن مُصيَّرة مسبقًا بشكل ثابت (روابط خاصة بها، وhreflang) — تفهرس Google كل لغة على حدة، لا الألمانية فقط.<br><br>• <strong>التوأم الذكي «اسأل يوسف · Neural Console»</strong> — أُعيد تصميم أداة الدردشة بالكامل: زر بحلقة ذكاء اصطناعي «تتنفّس»، إخفاء تلقائي عند التمرير، لوحة ملء الشاشة قابلة للسحب على الجوال، فتحها عبر Cmd/Ctrl+K، واقتراحات أسئلة واعية بسياق الصفحة.<br><br>• <strong>لوحة التحكّم «SPACE»</strong> — أداة إدارة بأسلوب Apple مع لوحة أوامر ⌘K، وثمانية أقسام (المشاريع، خارطة الطريق، سجلّ التغييرات، المدوّنة، الترجمات، الوسائط، معرفة الذكاء الاصطناعي، وضع الصيانة)، ولوحة صحة نظام حيّة، وسجلّ نشاط كامل.<br><br>• <strong>حصن الأمان</strong> — أربع طبقات أمان مستقلة تحمي لوحة التحكّم: قائمة وصول بيضاء، رمز PIN كعامل تحقّق ثانٍ، تقييد معدّل الطلبات، ورؤوس أمان — قبل أن تدير اللوحة الموقع الحقيقي.<br><br>• <strong>أقسام عامة جديدة</strong> — مدوّنة متعددة اللغات (Thoughts)، وسجلّ التغييرات العام هذا (أصبح الآن قابلًا للنقر مع بطاقات تفاصيل)، وخارطة طريق ديناميكية، وأداة حيّة لنشاط GitHub.<br><br>• <strong>إعادة تصميم «Calm Cinema»</strong> — الصفحة الرئيسية كلوحة واحدة متصلة بدلًا من كتل منفصلة، وهالة ضوئية تتبع مؤشر الفأرة في القسم الرئيسي، وانتقالات تمرير سينمائية، وخطوط مستضافة ذاتيًا، وطباعة مرنة.<br><br>• <strong>إمكانية الوصول وتطبيق ويب تقدّمي</strong> — روابط تخطٍّ، تحكّم كامل بلوحة المفاتيح، صفر انزياح في التخطيط عند التحميل، قابل للتثبيت ويعمل دون اتصال.<br><br>• <strong>وقدر كبير من الصقل</strong> — تم اختباره من الصفر على الجوال، وإصلاح عشرات الأخطاء الصغيرة، وفحص كل لغة وكل نمط (فاتح/داكن) مرّتين.`
  },
  {
    id: "019a1c4a-01fa-49fb-9f6b-784d6dba2152",
    version: "v1.3.0",
    date: "2026-05-29",
    category: "feature",
    title_de: `Roadmap & Changelog System`,
    title_en: `Roadmap & Changelog System`,
    title_ar: `نظام خارطة الطريق وسجل التغييرات`,
    description_de: `Vollständiges Roadmap-System: Supabase-gesteuert, Scope-Logik (Portfolio + Projekte), Prerender für SEO, Client-Renderer mit DE/EN/AR. Changelog-Komponente mit Kategorie-Badges. Admin: Drag & Drop Sortierung, "→ CL" Button, AR-Felder im Draft-Modal.`,
    description_en: `Full roadmap system: Supabase-driven, scope logic (portfolio + projects), prerender for SEO, client renderer with DE/EN/AR. Changelog component with category badges. Admin: drag & drop sorting, "→ CL" button, AR fields in the draft modal.`,
    description_ar: `نظام خارطة طريق كامل مدفوع بـ Supabase مع منطق النطاق للمحفظة والمشاريع، وعرض متعدد اللغات. مكون سجل التغييرات مع شارات الفئات.`
  },
  {
    id: "266eafb4-ad23-4546-bdea-037081dae907",
    version: "v1.2.0",
    date: "2026-05-28",
    category: "feature",
    title_de: `Projects & Media Manager`,
    title_en: `Projects & Media Manager`,
    title_ar: `إدارة المشاريع والوسائط`,
    description_de: `Projects CRUD: Admin UI für alle 5 Projekte, dynamischer Renderer (js/projects-data.js), Prerender für SEO, Build-Pipeline via GitHub Action. Media Manager v2: Repo-first Uploads, Admin-Commit-Flow, CV-Verwaltung, Supabase Storage Integration.`,
    description_en: `Projects CRUD: admin UI for all 5 projects, dynamic renderer (js/projects-data.js), prerender for SEO, build pipeline via GitHub Action. Media Manager v2: repo-first uploads, admin commit flow, CV management, Supabase Storage integration.`,
    description_ar: `إدارة المشاريع: واجهة مستخدم للتحكم في جميع المشاريع الخمسة مع عرض ديناميكي. إدارة الوسائط: رفع الصور والمستندات.`
  },
  {
    id: "873f10c2-e3c9-4d2d-b9dd-ea11a2884bf1",
    version: "v1.1.0",
    date: "2026-05-26",
    category: "feature",
    title_de: `Admin Panel — Infrastruktur & Kern-Features`,
    title_en: `Admin Panel — Infrastructure & Core Features`,
    title_ar: `لوحة الإدارة — البنية التحتية والميزات الأساسية`,
    description_de: `Admin Panel live auf admin.yusefbach.de (Vercel + Next.js + Supabase). GitHub OAuth Login. Maintenance Mode mit Notfall-Knopf, Multi-Sprache (DE/EN/AR), RTL, 30s-Polling. System Health Dashboard. Bot Memory Editor (yusef_brain.md). Translations Manager (DE/EN/AR, ~491 Keys).`,
    description_en: `Admin panel live at admin.yusefbach.de (Vercel + Next.js + Supabase). GitHub OAuth login. Maintenance Mode with emergency button, multi-language (DE/EN/AR), RTL, 30s polling. System Health dashboard. Bot Memory editor (yusef_brain.md). Translations Manager (DE/EN/AR, ~491 keys).`,
    description_ar: `لوحة الإدارة حية على admin.yusefbach.de. تسجيل دخول GitHub OAuth. وضع الصيانة مع زر الطوارئ ودعم RTL. لوحة صحة النظام. محرر ذاكرة البوت. إدارة الترجمات.`
  },
  {
    id: "0c91e01b-be54-47eb-92b4-3202517dfc4c",
    version: "v1.0.0",
    date: "2026-05-25",
    category: "refactor",
    title_de: `Architektur & TypeScript Migration`,
    title_en: `Architecture & TypeScript Migration`,
    title_ar: `هجرة البنية وTypeScript`,
    description_de: `Migration von statischem HTML zur datengetriebenen Engine. CSS in 6 Module aufgeteilt (2338 → 931 Zeilen main.css), project-base.css für alle Projektseiten, Web Components (app-header, app-footer, app-project-header), Inline-CSS eliminiert, lightbox.ts extrahiert. Kein Duplikat-Code mehr.`,
    description_en: `Migration from static HTML to a data-driven engine. CSS split into 6 modules (2338 → 931 lines main.css), project-base.css for all project pages, Web Components (app-header, app-footer, app-project-header), inline CSS eliminated, lightbox.ts extracted. No duplicate code.`,
    description_ar: `انتقال من HTML ثابت إلى محرك مدفوع بالبيانات. تقسيم CSS إلى 6 وحدات، مكونات الويب، إزالة التكرار في الكود.`
  }
];
